In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([3.14,2,1])

array([3.14, 2.  , 1.  ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a2=np.array([[1,2,3],
             [4,5,6]])

In [7]:
a2.shape

(2, 3)

In [8]:
a2.ndim

2

In [9]:
a2.dtype

dtype('int64')

In [10]:
a2.size

6

In [11]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

In [13]:
np.arange(1,10,4)

array([1, 5, 9])

In [14]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### random


In [16]:
import numpy as np

In [17]:
np.random.random((1,4))

array([[0.06695117, 0.53912732, 0.80927816, 0.88770834]])

In [18]:
np.random.random((1,4))

array([[0.47947197, 0.23617856, 0.72112327, 0.66978047]])

In [19]:
#Seed
np.random.seed(0)
np.random.random((1,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318]])

In [20]:
np.random.normal(0,1,(3,3))

array([[ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [21]:
np.random.randint(0,100,(1,10))

array([[77, 72,  9, 20, 80, 69, 79, 47, 64, 82]])

### Array index and slice


In [22]:
x1=np.random.randint(0,20, (1,6))

x2=np.random.randint(20,size=6)

In [23]:
x1


array([[ 3, 17, 19, 19, 19, 14]])

In [24]:
x2

array([ 7,  0,  1,  9,  0, 10])

In [25]:
x2[4]

0

### slicing

In [36]:
x2[1:3]

array([0, 1])

In [38]:
x3=np.random.randint(0,20,(3,4))

In [41]:
x3[1,3]

13

### reshape and transpose

In [48]:
grid=np.arange(1,10)
grid,grid.shape

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), (9,))

In [49]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x= np.array([1,2,3])

In [51]:
x=x.reshape((1,3))
x

array([[1, 2, 3]])

In [53]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [54]:
x.T

array([[1, 3],
       [2, 4]])

### concatenation and splitting


In [55]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [58]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [59]:
grid = np.array([[1,2],[3,4]])
grid1 = np.array([[5,6],[7,8]])

In [61]:
np.concatenate((grid,grid1))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [62]:
np.concatenate((grid,grid1), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [63]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

### broacasting and vectorized operations


In [66]:
np.arange(1,4)+5 #broadcasting

array([6, 7, 8])

In [68]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### Manipulating and Comparing arrays

In [69]:
np.sum(np.array([1,2,3]))

6

In [70]:
# do lech chuan 
np.std(np.array([600,470,170,430,300]))

147.32277488562318

In [71]:
# phuong sai
np.var(np.array([600,470,170,430,300]))

21704.0

### Sorting 


In [72]:
x=np.array([2,1,23,4,5,6,7,74,3,1])


In [75]:
np.sort(x)

array([ 1,  1,  2,  3,  4,  5,  6,  7, 23, 74])

In [76]:
np.argsort(x)

array([1, 9, 0, 8, 3, 4, 5, 6, 2, 7])

In [79]:
np.random.seed(42)
A=np.random.randint(0,10,size=(4,6))

In [80]:
A

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [81]:
np.sort(A,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [82]:
np.sort(A,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### linear algebra


In [83]:
A=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
B=np.array([[6,5],
           [4,3],
           [2,1]])

In [84]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [85]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [91]:
np.concatenate((np.arange(1,32),np.arange(1,30)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
A = np.arange(1,32) 
B = np.arange(1,30)
C = np.arange(1,31) 
np.concatenate((A,B,A,C,A,C,A,A,C,A,C,A))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13

In [93]:
sales_amounts= np.array([[12,10,0],
                        [3,3,7],
                        [9,19,18],
                        [4,6,12],
                        [1,6,7]
                        ])

In [94]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,index=["Monday","Tuesday","Wednesday","Thursday","Friday"],columns=["Butter","Salad","Chiken"])

In [95]:
weekly_sales


Butter  Salad  Chiken
Monday         12     10       0
Tuesday         3      3       7
Wednesday       9     19      18
Thursday        4      6      12
Friday          1      6       7

In [99]:
# create a price array
prices=np.array([10,5,30]).reshape(1,3)
prices_array=pd.DataFrame(prices,index=["Price"],columns=["Butter","Salad","Chiken"])

In [100]:
prices_array


Butter  Salad  Chiken
Price      10      5      30

In [103]:
total_prices=weekly_sales@prices.T

In [104]:
total_prices


0
Monday     170
Tuesday    255
Wednesday  725
Thursday   430
Friday     250

In [105]:
weekly_sales["total_prices"]=total_prices
weekly_sales


Butter  Salad  Chiken  total_prices
Monday         12     10       0           170
Tuesday         3      3       7           255
Wednesday       9     19      18           725
Thursday        4      6      12           430
Friday          1      6       7           250

In [107]:
np.sum(weekly_sales["total_prices"])

1830

In [108]:
days=np.concatenate((A,B,A,C,A,C,A,A,C,A,C,A))
days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13